# Database connection information JDBC url
spring.datasource.url: jdbc:sqlite:src/main/resources/sample.db
 # Database driver name
spring.datasource.driver-class-name: org.sqlite.JDBC
# Dialect
spring.jpa.database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.generate-ddl: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.open-in-view: true
